fix: non-empty project description for diff
keboola/keboola-as-code pull request #1817
Opened 2024-06-04 09:58 UTC by hosekpeter

Jira: [PSGO-583](https://keboola.atlassian.net/browse/PSGO-583)

**Changes:**
- fixed non-empty project description for diff

-----------

2024-06-05 09:21 UTC, Matovidlo approved these changes
LGTM

2024-06-05 09:31 UTC, michaljurecko requested changes

2024-06-05 09:31 UTC, michaljurecko commented on internal/pkg/diff/diff.go
> +			ok := regexp.MustCompile(`^\s*$`).MatchString(desc)
Please, use `regexpcache`, it can be called many times during one CLI command.

2024-06-05 09:31 UTC, michaljurecko commented on internal/pkg/diff/diff.go
> +		cmpopts.AcyclicTransformer("projectDescription", func(branchMetadata model.BranchMetadata) model.BranchMetadata {
At least one E2E test is needed.

2024-06-06 12:44 UTC, michaljurecko approved these changes
:heavy_check_mark: I tried to disable new code, and the E2E test failed.

Good work!

![image](https://github.com/keboola/keboola-as-code/assets/19371734/bd3f9eac-e5bc-457c-b013-31e3b49b0ddd)

2024-06-06 12:48 UTC, merged