Fix data apps timeouts
keboola/keboola-as-code pull request #1856
Opened 2024-06-18 11:54 UTC by Matovidlo

Jira: [PSGO-686](https://keboola.atlassian.net/browse/PSGO-686)

**Changes:**
- Set data apps timeout for websocket differently than for HTTP upstream handler.
- HTTP root span contains attributes.

-----------

2024-06-18 13:49 UTC, michaljurecko commented on internal/pkg/service/appsproxy/config/config.go
> +	AppTimeouts      Timeouts          `configKey:"appTimeouts" configUsage:"Timeouts set for application interactions"`
Naming :thinking: 

- `appTimeouts.httpUpstreamTimeout`, `-app-timeouts-http-upstream-timeout`
- `appTimeouts.wessocketUpstreamTimeout`, `-app-timeouts-websocket-upstream-timeout`

Suggestion:
- `httpUpstreamTimeout`, `-http-upstream-timeout`
- `wsUpstreamTimeout`, `-ws-upstream-timeout`

Or:
- `upstream.httpTimeout`, `-upstream-http-timeout`
- `upstream.wsTimeout`, `-upstream-ws-timeout`

Or:
- `httpTimeout`, `-http-timeout`
- `wsTimeout`, `-ws-timeout`

You can use `configKey:"-"` if you want a specific struct for timeouts, but I think that the structure is not necessary.

2024-06-18 16:56 UTC, michaljurecko requested changes
:heavy_check_mark: naming

... but, the test is unstable:

![image](https://github.com/keboola/keboola-as-code/assets/19371734/73c30685-4948-494d-8151-651d6b064c94)

2024-06-19 07:49 UTC, Matovidlo commented
@michaljurecko @jachym-tousek-keboola I have created task https://keboola.atlassian.net/browse/PSGO-688 to solve the test issue. Michal suggest to use waitgroup instead of timeout. However it would need to refactor handler and test to work with each other. Now they are not connected and it's a bug so let's merge it and release it.

2024-06-19 08:04 UTC, michaljurecko approved these changes

2024-06-19 09:05 UTC, merged