fix: Fix issue on template test create
keboola/keboola-as-code pull request #2039
Opened 2024-09-24 09:10 UTC by hosekpeter

Jira: [PSGO-788](https://keboola.atlassian.net/browse/PSGO-788)

**Changes:**
- creating a missing files/folder for command `kbc template create test`

-----------

This PR addresses a template issue. The problem was that the files (`manifest.json, meta.json, description.md`) were missing after running the command `kbc template create test`. That's why I added the logic to create these files.

[PSGO-788]: https://keboola.atlassian.net/browse/PSGO-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-24 11:01 UTC, hosekpeter commented on internal/pkg/template/template.go
> +			}
The folder 'test' wasn't created. The missing files (.keboola/manifest.json, main/meta.json...) must be stored in the tests folder. 

<img width="233" alt="image" src="https://github.com/user-attachments/assets/29a48c83-eff9-461a-a0e1-3cfcb3ef2123">

2024-09-24 12:12 UTC, Matovidlo requested changes
Just add test that folder with files exists.

2024-09-24 12:57 UTC, hosekpeter commented
@Matovidlo tests [9450b33](https://github.com/keboola/keboola-as-code/pull/2039/commits/9450b33e77f5df87b395ef207f5db923cb2ec53e)

2024-09-25 07:52 UTC, Matovidlo approved these changes

2024-09-25 08:06 UTC, merged