feat: Rollback version endpoint for source
keboola/keboola-as-code pull request #2096
Opened 2024-10-14 13:48 UTC by hosekpeter

Jira: [PSGO-779](https://keboola.atlassian.net/browse/PSGO-779)

**Changes:**
- added an endpoint
- added E2E tests

-----------

[PSGO-779]: https://keboola.atlassian.net/browse/PSGO-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-14 14:45 UTC, Matovidlo approved these changes
LGTM

2024-10-15 07:52 UTC, jachym-tousek-keboola requested changes

2024-10-15 07:52 UTC, jachym-tousek-keboola commented on test/stream/api/source/rollback-version-404/005-poll-rollback/expected-response.json
> +  "error": "Source version \"my-source/0000012345\" not found in the branch."
The check if version exists should happen immediately and not only in the background task. `004-rollback-version` should return `404`. Enable and Disable on Source and Sink work this way as well.

2024-10-15 11:43 UTC, jachym-tousek-keboola commented on test/stream/api/source/rollback-version-ok/005-rollback-version/request.json
> +
```suggestion

```

2024-10-15 11:44 UTC, jachym-tousek-keboola commented on test/stream/api/source/rollback-version-ok/007-list-source-versions/expected-response.json
> +
```suggestion
```

2024-10-15 11:44 UTC, jachym-tousek-keboola commented on test/stream/api/source/rollback-version-ok/005-rollback-version/request.json
> +
```suggestion
```

2024-10-15 12:15 UTC, merged