fix: Name in ECR repository and tag should be different
keboola/keboola-as-code pull request #2179
Opened 2024-12-10 15:35 UTC by Matovidlo

**Changes:**
- It does not override production image.

-----------

2024-12-10 16:53 UTC, hosekpeter approved these changes
LGTM

2024-12-11 08:21 UTC, kacurez commented
toto uz teda nebudes potrebovat nasadit ci?  https://keboolaglobal.slack.com/archives/C055K9CRFDX/p1733849063356059?thread_ts=1733834074.491109&cid=C055K9CRFDX

2024-12-11 09:49 UTC, Matovidlo commented
@kacurez neviem ci to pomoze ci nie, niekde sa zvysil memory consumption a neviem teda ci je to imagom (skor nie) alebo kodom.

2024-12-11 10:30 UTC, kacurez commented
pozeram na to a je vidiet ze je nasadeny image s tym racerom:
Zbuildoval sa s sha `6df78715eb1c48d5b...`
![image](https://github.com/user-attachments/assets/884a7327-645e-47b2-9544-60f3f3a6d62c)
a [vidim](https://app.datadoghq.eu/container-images?query=stream%20AND%20image_name%3Aus-central1-docker.pkg.dev%2Fkeboola-prod-artifacts%2Fkeboola-as-code%2Fstream-service&inspect=us-central1-docker.pkg.dev%2Fkeboola-prod-artifacts%2Fkeboola-as-code%2Fstream-service%40sha256%3A6df78715eb1c48d5b6be746b80337699929be9a8ce922ce033794ae2b1f7acc6&panelTab=containers&view=explorer) ze je nasadeny 
![image](https://github.com/user-attachments/assets/1c74e7dc-641e-43a3-8040-815be6f7ea8b)


Co je ale zvlastne ze napr v GCP [repu](https://console.cloud.google.com/artifacts/docker/keboola-prod-artifacts/us-central1/keboola-as-code?project=keboola-prod-artifacts) vobec nevidim ten `-race` image iba `stream-service`
![image](https://github.com/user-attachments/assets/bf9ad550-5bb6-4c00-909b-38441119510e)

2024-12-11 10:33 UTC, kacurez approved these changes
nie som si isty ci to pomozme ale mozme skusit, je vidiet ze sa nasadil image s tym race 
 ale pod prod tagom https://keboolaglobal.slack.com/archives/C055K9CRFDX/p1733913074422449?thread_ts=1733834074.491109&cid=C055K9CRFDX

2024-12-11 11:04 UTC, wokoman requested changes

2024-12-11 11:04 UTC, wokoman commented on .github/actions/push-image-aws-azure-gcp/action.yml
> +        docker tag ${{ inputs.imageName }}:${{ inputs.imageTag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepository }}:$TAG
```suggestion
        docker tag ${{ inputs.imageName }}:${{ inputs.imageTag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepository }}:${{ inputs.imageTag }}
```

Plus i ty dva dole 🙈

2024-12-11 11:10 UTC, Matovidlo commented on .github/actions/push-image-aws-azure-gcp/action.yml
> +        docker tag ${{ inputs.imageName }}:${{ inputs.imageTag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepository }}:$TAG
dik

2024-12-11 11:10 UTC, Matovidlo commented on .github/actions/push-image-aws-azure-gcp/action.yml
> +        docker tag ${{ inputs.imageName }}:${{ inputs.imageTag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepository }}:$TAG
https://github.com/keboola/keboola-as-code/pull/2179/commits/cfcb37b26d64bb208c10b388b0dd8405cda7329c

2024-12-11 11:12 UTC, wokoman approved these changes
Fabulozni, dik!

2024-12-11 11:26 UTC, merged