feat: Add apps proxy local development docs
keboola/keboola-as-code pull request #2187
Opened 2024-12-17 08:45 UTC by Matovidlo

Jira: [PSGO-919](https://keboola.atlassian.net/browse/PSGO-919)

**Changes:**
- Add apps proxy documentation for local development.
- Include short overview of apps proxy, what is it, why we have it and how to use it.
- Add basic configuration of the apps proxy for development on local machine.

-----------

2025-01-02 11:28 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +- Typicall usage is to perform OIDC login through some OIDC provider (e.g Microsoft login, google login etc.)
```suggestion
- Typicall usage is to perform OIDC login through some OIDC provider (e.g Microsoft login, Google login etc.)
```

2025-01-02 11:32 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +docker compose run --rm --service-ports dev --net=my-test bash
This doesn't work for me:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--net=my-test": executable file not found in $PATH: unknown
```

I'm guessing some additional setup is necessary?

2025-01-02 11:34 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +make run-app-proxy
This doesn't work either.

```
make: *** No rule to make target 'run-app-proxy'.  Stop.
```

Looks like a typo.

```suggestion
make run-apps-proxy
```

2025-01-02 11:35 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +make run-app-proxy
However `make run-apps-proxy` doesn't work either:

```
make[1]: Entering directory '/code'
CGO_ENABLED=0 go build -v -mod mod -ldflags "-s -w" -o "./target/apps-proxy/proxy" ./cmd/apps-proxy
# cd /code; git status --porcelain
fatal: detected dubious ownership in repository at '/code'
To add an exception for this directory, call:

        git config --global --add safe.directory /code
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
make[1]: *** [Makefile:52: build-apps-proxy] Error 1
make[1]: Leaving directory '/code'
```

2025-01-02 11:44 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +  --env TARGET_HOST=<containerid> \
Remove this extra step to obtain container id. It should be possible to just replace `<containerid>` with this:

```
$(docker ps -aqf "name=dev")
```

2025-01-02 11:45 UTC, jachym-tousek-keboola requested changes
Good work, I just want the containerid thing automated.

2025-01-06 07:42 UTC, hosekpeter approved these changes

2025-01-06 13:56 UTC, Matovidlo commented on docs/apps-proxy/overview.md
> +- Typicall usage is to perform OIDC login through some OIDC provider (e.g Microsoft login, google login etc.)
Fixed

2025-01-06 13:57 UTC, Matovidlo commented on docs/apps-proxy/overview.md
> +make run-app-proxy
Fixed. I found that it is more beneficial to uncomment `command` section in docker compose and run it using `docker compose up dev`

2025-01-06 13:57 UTC, Matovidlo commented on docs/apps-proxy/overview.md
> +  --env TARGET_HOST=<containerid> \
Thanks for advice. I went for docker compose instead. Check last commit

2025-01-06 13:58 UTC, Matovidlo commented on docs/apps-proxy/overview.md
> +docker compose run --rm --service-ports dev --net=my-test bash
Reworked using `network` in docker compose. It is more reliable.

2025-01-06 14:00 UTC, Matovidlo commented
@jachym-tousek-keboola I have changed the docker mixed setup with docker compose to only docker compose. There is only one adjustement needed and it is uncommenting of `command` step in docker compose. Otherwise rest of workflow should work.
I adjusted provisioning of dev as it was not possible to override options by the `environment` of `docker compose` `dev` container.

2025-01-07 12:57 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +           make run-apps-proxy"
I don't think the git config should be here, I think that needs to be run outside of the container manually.

2025-01-07 13:35 UTC, Matovidlo commented on docs/apps-proxy/overview.md
> +           make run-apps-proxy"
You cannot run it in `command` section without this. I am not sure why it is required as it was not required before. Any suggestions how to fix this?

2025-01-08 13:12 UTC, jachym-tousek-keboola commented on docs/apps-proxy/overview.md
> +           make run-apps-proxy"
Apparently git checks if the user running the git command is the owner of the repository and throws "dubious ownership" error. I checked online and this seems to be the recommended fix. Okay then.

2025-01-08 13:12 UTC, jachym-tousek-keboola approved these changes

2025-01-08 13:58 UTC, merged