List Workspaces CLI command
keboola/keboola-as-code pull request #841
Opened 2022-09-27 15:27 UTC by jprochazk

https://keboola.atlassian.net/browse/KAC-232

Changes:

- Implement `remote workspace list` command

2022-09-27 15:28 UTC, jprochazk commented
Tady vůbec netuším, jak to otestovat. Ty sandboxy jsou uložený mimo projekt (nejsou to configy).

2022-09-27 15:30 UTC, webrouse commented
Otestovat manualne a k testom sa vratit, ked bude implementovany aj `delete`.
Idem to vyskusat.

2022-09-28 10:20 UTC, jprochazk commented
Změny:
- Odstranil jsem ten test a vytvořil pro to task https://keboola.atlassian.net/browse/KAC-250
- `invalid workspace` error je teď debug hláška
- Output má každý workspace na jednom řádku
- Load configů a instances teď běží parallelně

2022-09-29 04:54 UTC, webrouse commented on pkg/lib/operation/project/remote/workspace/list.go
> +type listDeps interface {
tento interface zvykneme nazyvat `dependencies` a metodu` Run` a package `list`, vid ostatne operations.

2022-09-29 04:54 UTC, webrouse commented on pkg/lib/operation/project/remote/workspace/list.go
> +	}()
Ako sme rozpravali (niekde?) s @JakubMatejka 

Z `go-client` by sme mali vracat uz "hotovy` sandbox, ktory obsahuje informacie z oboch APIs.
Tj zo Storage API tusim iba name.

Tj. tento kod patri skor do `go-client`.
Mozno by stalo za to mat aktualny pkg `sandboxesapi` a aj novy `sandbox` (kde by boli tie agregovane funkcie).

Mozeme sa o tom este pobavit na standupe.

2022-09-29 04:54 UTC, webrouse commented on pkg/lib/operation/project/remote/workspace/list.go
> +		}
Ak sa spravi nova struktura (napr. `sandbox.Sandbox`), ktora zahrna `instance` aj `config`,... tak by mohla mat metodu `String()` a tento kod by bol tam (bez tych uvodnych spaces).

2022-10-07 12:54 UTC, jprochazk commented
Netuším, proč failuje lint. Lokálně mi běží.

2022-10-07 12:58 UTC, jprochazk commented
Aha, vidím, že jsme vyměnili `goimports` za `gci`

2022-10-07 13:05 UTC, jprochazk commented
Ten ale nedokážu nastavit v IDE, mám tam jen tyhle možnosti:
![image](https://user-images.githubusercontent.com/1665677/194560552-da30e215-78db-4542-9442-3bdf7e81a929.png)

@JakubMatejka

2022-10-07 13:14 UTC, JakubMatejka commented
No je tam špatný pořadí, `make fix` s tím udělá tohle:
![CleanShot 2022-10-07 at 15 13 22](https://user-images.githubusercontent.com/215660/194562208-eaa730d9-23dd-4195-84fc-2412e0d3de47.jpg)

2022-10-07 13:15 UTC, JakubMatejka commented
Co se týče nastavení IDE, tak v IntelliJ mám `goimports` ale je to manuálně donastavený takto:
![CleanShot 2022-10-07 at 15 14 22](https://user-images.githubusercontent.com/215660/194562428-33516309-de85-48ef-8796-1d74c5176b15.jpg)

2022-10-07 13:24 UTC, JakubMatejka commented
BTW. máš nějakej divnej email v git logu, máš to dobře nastavený?

![CleanShot 2022-10-07 at 15 23 29](https://user-images.githubusercontent.com/215660/194564150-a6ad9394-f3eb-48f0-ac53-3a1aafc4a479.jpg)

2022-10-07 13:25 UTC, jprochazk commented
Ten email je vygenerovaný od githubu, je to anti-spam measure.

2022-10-07 13:45 UTC, michaljurecko commented
Je to nastavene tu:
![image](https://user-images.githubusercontent.com/19371734/194568014-25d0626a-b32d-4ee5-98d7-047fc4bd14ad.png)

`goimports` nefunguju vzdy dobre, vid napr.:
https://github.com/golang/go/issues/20818

Najlepsie by bolo nastavit si `visual studio` aby pouzivalo `golangci-lint`
https://golangci-lint.run/usage/integrations/

Staci takto?

2022-10-07 14:44 UTC, jprochazk commented
Proč mi lokálně nefailuje `make lint`? `make fix` taky nic.

2022-10-07 14:51 UTC, JakubMatejka commented
To se mi ale vlastně taky někdy dělo. 🤔 Myslel jsem že mám lokálně nějakou starší verzi golinteru, ale vlastně nevím.

2022-10-07 14:52 UTC, jprochazk commented
gci mám v1.50.0

2022-10-07 14:53 UTC, jprochazk commented
Ty options pro import sorting vscode nemá.

2022-10-07 14:53 UTC, michaljurecko commented
@jprochazk @JakubMatejka neviem, mozete skusit prosim spustit gci priamo?
```
go install github.com/daixiang0/gci@latest
```

```
gci diff -s "standard,default,prefix(github.com/keboola/keboola-as-code)" ./pkg/lib/operation/project/remote/workspace/create.go
```

----

Ak to pojde ocakavane, tak skuste vypnut v nastaveniach ostatne linters a spustit to.
Ak pojde aj to, tak je potrebne najst, ktory iny linter robi problemy, napr. mozno to vyriesi vypnutie `gofumpt`.

2022-10-07 14:54 UTC, JakubMatejka commented
Myslím to teda tak že lokálně nic, ale až v Docker kontejneru to začalo hlásit chybu.

2022-10-07 14:55 UTC, jprochazk commented
![image](https://user-images.githubusercontent.com/1665677/194583492-9fcb1b55-dd3b-42b4-9db1-5e132bee2eab.png)

2022-10-07 14:55 UTC, michaljurecko commented
Verzia? 
![image](https://user-images.githubusercontent.com/19371734/194583652-34bc1194-6b93-4a93-ab33-965121c89905.png)

2022-10-07 14:55 UTC, jprochazk commented
Btw, language server mi hlásí error
```
[Error - 4:52:26 PM] 2022/10/07 16:52:26 tidy: diagnosing file:///home/jan/work/keboola-as-code/go.mod: err: exit status 1: stderr: go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
```

2022-10-07 14:56 UTC, jprochazk commented
![image](https://user-images.githubusercontent.com/1665677/194583725-a3b3af6d-de51-4f7c-85c8-d3dcc73ee9b3.png)

2022-10-07 14:56 UTC, michaljurecko commented
nemas nainstalovane ine `Go`? 
![image](https://user-images.githubusercontent.com/19371734/194583853-3df303b2-a1e0-4f1f-b432-8810f6ab01fb.png)

2022-10-07 14:58 UTC, michaljurecko commented
Este mozes skusit debug flag `gci diff -d ...`

2022-10-07 14:59 UTC, michaljurecko commented
![image](https://user-images.githubusercontent.com/19371734/194584407-dd7be5be-b08f-46f9-9037-403f5c95e6f8.png)

2022-10-07 15:02 UTC, jprochazk commented
Měl jsem 1.18, dal jsem upgrade na 1.19 a pořád stejný output `gci diff -s ...`

2022-10-07 15:03 UTC, jprochazk commented
`gci diff -s ... -d`
![image](https://user-images.githubusercontent.com/1665677/194585269-52d947f5-2377-4787-a2b4-0ff1ab6e5d96.png)

2022-10-07 15:24 UTC, michaljurecko commented
Este mi teraz doslo, ze som tam zabudol dat `blank` (prazdny riadok) ... pokracujeme v pondelok:

```
 gci diff -s "standard,blank,default,blank,prefix(github.com/keboola/keboola-as-code)" ./pkg/lib/operation/project/remote/workspace/create.go
 ```

2022-10-10 06:45 UTC, jprochazk commented
```
$ gci diff -d -s "standard,blank,default,blank,prefix(github.com/keboola/keboola-as-code)" ./pkg/lib/operation/project/remote/workspace/list/operation.go
2022-10-10T08:42:43.406+0200    DEBUG   gci/gci.go:115  Loaded File: pkg/lib/operation/project/remote/workspace/list/operation.go
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{24 34  context} to section standard
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{35 41  fmt} to section standard
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{78 120  github.com/keboola/go-client/pkg/client} to section default
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{121 169  github.com/keboola/go-client/pkg/sandboxesapi} to section default
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{170 216  github.com/keboola/go-client/pkg/storageapi} to section default
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{217 271  github.com/keboola/keboola-as-code/internal/pkg/log} to section prefix(github.com/keboola/keboola-as-code)
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{272 332  github.com/keboola/keboola-as-code/internal/pkg/telemetry} to section prefix(github.com/keboola/keboola-as-code)
2022-10-10T08:42:43.406+0200    DEBUG   format/format.go:41     Matched import &{43 76  go.opentelemetry.io/otel/trace} to section default
--- pkg/lib/operation/project/remote/workspace/list/operation.go
+++ pkg/lib/operation/project/remote/workspace/list/operation.go
@@ -4,11 +4,11 @@
        "context"
        "fmt"
 
-       "go.opentelemetry.io/otel/trace"
-
        "github.com/keboola/go-client/pkg/client"
        "github.com/keboola/go-client/pkg/sandboxesapi"
        "github.com/keboola/go-client/pkg/storageapi"
+       "go.opentelemetry.io/otel/trace"
+
        "github.com/keboola/keboola-as-code/internal/pkg/log"
        "github.com/keboola/keboola-as-code/internal/pkg/telemetry"
 )
```

2022-10-10 07:00 UTC, jprochazk commented
Pokud teda upravím ten `build/ci/golangci.yml` aby měl ty blanks:
```yaml
gci:
  sections:
    - standard # Captures all standard packages if they do not match another section.
    - blank
    - default # Contains all imports that could not be matched to another section type.
    - blank
    - prefix(github.com/keboola/keboola-as-code)
```
Tak mám tenhle output:
```
/code > make lint
if [ ! -d "internal/pkg/api/server/templates/http" ] || [ -z  ]; then bash ./scripts/generate-templates-api.sh; fi
/code
Generating templates API ...
Ok.

bash ./scripts/lint.sh
/code
Running go vet ...
Running go mod tidy/verify ...
all modules verified
Ok. go.mod and go.sum are valid.

Running golangci-lint ...
api/templates/design.go:4: File is not `gci`-ed with --skip-generated -s standard,blank,default,blank,prefix(github.com/keboola/keboola-as-code) (gci)
import (
        _ "goa.design/goa/v3/codegen/generator"
        . "goa.design/goa/v3/dsl"
        "goa.design/goa/v3/eval"
        "goa.design/goa/v3/expr"
        "goa.design/goa/v3/http/codegen/openapi"
        cors "goa.design/plugins/v3/cors/dsl"
api/templates/design.go:12: File is not `gci`-ed with --skip-generated -s standard,blank,default,blank,prefix(github.com/keboola/keboola-as-code) (gci)
        _ "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/anytype"
        _ "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/dependencies"
        _ "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/genericerror"
        "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/oneof"
        _ "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/oneof"
        _ "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/operationid"
        . "github.com/keboola/keboola-as-code/internal/pkg/api/server/templates/extension/token"
        "github.com/keboola/keboola-as-code/internal/pkg/json"
)

pkg/lib/operation/project/remote/workspace/list/operation.go:7: File is not `gci`-ed with --skip-generated -s standard,blank,default,blank,prefix(github.com/keboola/keboola-as-code) (gci)
        "go.opentelemetry.io/otel/trace"

Please fix ^^^ errors. You can try run "make fix".

make: *** [Makefile:57: lint] Error 1
```

2022-10-10 07:03 UTC, michaljurecko commented
asi bude lepsie si zavolat (to blank tam teda asi byt nema, sorry, zle som to pochopil)

2022-10-10 08:44 UTC, JakubMatejka requested changes
Zkoušel jsi to buildnout a spustit? 🙂 
![CleanShot 2022-10-10 at 10 44 06](https://user-images.githubusercontent.com/215660/194828570-3cf3c8a9-f5b4-477e-a78b-2449f1146b55.jpg)

```
DEBUG	Unexpected panic: runtime error: invalid memory address or nil pointer dereference
DEBUG	Trace:
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/opt/go/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/keboola/keboola-as-code/internal/pkg/utils.ProcessPanic({0x104d98720?, 0x10561fbf0?}, {0x104ea33f0, 0x1400000d020}, {0x1400051c360, 0x5c})
	/Users/jakubm/Keboola/keboola-as-code/internal/pkg/utils/panic.go:60 +0x230
github.com/keboola/keboola-as-code/internal/pkg/cli/cmd.(*RootCommand).tearDown(0x14000180230, 0x104ea33f0?, {0x104d98720?, 0x10561fbf0?})
	/Users/jakubm/Keboola/keboola-as-code/internal/pkg/cli/cmd/cmd.go:391 +0x9c
github.com/keboola/keboola-as-code/internal/pkg/cli/cmd.(*RootCommand).Execute.func1()
	/Users/jakubm/Keboola/keboola-as-code/internal/pkg/cli/cmd/cmd.go:226 +0x58
panic({0x104d98720, 0x10561fbf0})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:884 +0x204
github.com/keboola/go-client/pkg/sandboxesapi.SandboxWithConfig.String({0x0?, 0x14000d983c0?})
	/Users/jakubm/Keboola/keboola-as-code/vendor/github.com/keboola/go-client/pkg/sandboxesapi/sandbox.go:25 +0x2c
github.com/keboola/keboola-as-code/pkg/lib/operation/project/remote/workspace/list.Run({0x104e9be30, 0x14000194008}, {0x10d5e80c0, 0x14000d36020})
	/Users/jakubm/Keboola/keboola-as-code/pkg/lib/operation/project/remote/workspace/list/operation.go:42 +0x2f4
github.com/keboola/keboola-as-code/internal/pkg/cli/cmd/remote/workspace.ListCommand.func1(0x140001ad400?, {0x104a125c5?, 0x0?, 0x0?})
	/Users/jakubm/Keboola/keboola-as-code/internal/pkg/cli/cmd/remote/workspace/list.go:33 +0x128
github.com/spf13/cobra.(*Command).execute(0x140001ad400, {0x10583c0e0, 0x0, 0x0})
	/Users/jakubm/Keboola/keboola-as-code/vendor/github.com/spf13/cobra/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000394a00)
	/Users/jakubm/Keboola/keboola-as-code/vendor/github.com/spf13/cobra/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jakubm/Keboola/keboola-as-code/vendor/github.com/spf13/cobra/command.go:918
github.com/keboola/keboola-as-code/internal/pkg/cli/cmd.(*RootCommand).Execute(0x14000180230)
	/Users/jakubm/Keboola/keboola-as-code/internal/pkg/cli/cmd/cmd.go:229 +0x64
main.main()
	/Users/jakubm/Keboola/keboola-as-code/cmd/kbc/main.go:24 +0xb8
```

2022-10-10 08:47 UTC, JakubMatejka commented
Aha, vypadá to že mám nějakou Storage konfiguraci ke které asi není sandbox? 🤔 
![CleanShot 2022-10-10 at 10 46 59](https://user-images.githubusercontent.com/215660/194829071-567d4ef1-6eee-4bf4-9fe0-806833e8d40e.jpg)

2022-10-10 08:49 UTC, JakubMatejka commented
Jo to se může stát. Není to standardní, nemělo by se to dít, ale je třeba s tím počítat. (A takový workspace ignorovat.)

2022-10-10 08:53 UTC, jprochazk commented
To by se mělo ignorovat už v `go-client`. Můžeš mě pozvat do toho projektu?

2022-10-10 08:59 UTC, JakubMatejka commented
@jprochazk aha, jasně. Je to https://connection.north-europe.azure.keboola.com/admin/projects/1268 přístup tam už máš

2022-10-10 09:07 UTC, jprochazk commented
https://github.com/keboola/go-client/pull/31

2022-10-10 09:51 UTC, jprochazk commented
> @jprochazk aha, jasně. Je to https://connection.north-europe.azure.keboola.com/admin/projects/1268 přístup tam už máš

Po upgrade mám tenhle output, funguje ti to už?
```
$ ./target/keboola-cli_linux_amd64/kbc remote workspace list
Loaded env file ".env".
Storage API host "connection.north-europe.azure.keboola.com" set from ENV.
Storage API token set from ENV.
Loading workspaces, please wait.
Found workspaces:
  ID: 1699268, Type: python, Size: small, Name: test
  ID: 4429297, Type: snowflake, Name: test-snowflake
  ID: 731093, Type: python-mlflow, Name: register model
```

2022-10-10 10:15 UTC, jprochazk commented
Nesouhlasím s tím, že by tam toho bylo moc. U templates mi zase přijde že je tam zbytečně moc "dead space". V malým terminal window se mi tam nevleze ani jeden celý template. Jakmile máš 3+ tak už je to docela extrém. Určitě bysme to měli nějak standardizovat, ale chtěl bych to takhle zatím nechat a možná se k tomu ještě vrátit někdy jindy.

2022-10-10 10:33 UTC, michaljurecko commented
:slightly_smiling_face: ja som nad tym tiez rozmyslal, ale neprisiel som na jednoznacne riesenie:
- napr. nemal by byt `name` prvy? ked bude mat user 20x workspace, bude sa v tom schopny zorientovat
- ale mozno to nie je nieco co my riesit STDOUT, ale skor nejaky "lepsi" interface, kde sa da aj vyhladavat (alebo user pouzije nejaky iny CLI tool a tam presmeruje vystup)
- takze neviem, osobne mi pride vystup pri `templates` prehladnejsi, ... delimiter sa tam moze pridat .... nevadi mi ani, ked by som si to v pripade potreby presmeroval do suboru a vyhladaval v tom cez VSCode
- takze som vam velmi nepomohol :smiley:

2022-10-10 10:38 UTC, michaljurecko commented
Ako to riesi napr. Kubernetes CLI?

2022-10-10 10:42 UTC, jprochazk commented
Takový "compact table" interface:
![image](https://user-images.githubusercontent.com/1665677/194848514-d29bf815-cdff-435e-bfd6-8e59b3ed12be.png)

2022-10-10 10:46 UTC, michaljurecko commented
Pri workspace by sa to dalo, pri templates uz nie + name je prvy.

2022-10-10 10:47 UTC, michaljurecko commented
Ale mozeme to vyriesit aj neskor a dat do backlogu, a pozriet sa aj na ostatne prikazy.

2022-10-10 11:03 UTC, jprochazk commented
Jen nechci zůstat tady zaseklý, tenhle PR obsahuje víc než jen `workspace list` implementaci, takže to blokuje další věci. Byl bych pro to dát do backlogu, není potřeba to řešit hned.

2022-10-10 11:14 UTC, JakubMatejka commented
No jak jsem psal, tak je to takhle imho nepřehledný a k tomu jsem velký zastánce konzistentnosti. Pokud se na tom ale shodneme, tak to nechme a řešme později. 🤷‍♂️

Tak co třeba dát první název jak píše Michal a ostatní parametry trochu upozadit, třeba oddělit závorkama?
```
test (ID: 1699268, Type: python, Size: small)
test-snowflake (ID: 4429297, Type: snowflake)
register model (ID: 731093, Type: python-mlflow)
```

2022-10-10 11:35 UTC, jprochazk commented
Pls teď se o tom nebavme, jak říká Michal, je asi potřeba vymyslet lepší interface pomocí kterýho to budeme vypisovat, podobně jako máme interface na selecty 🙂. V tom interface můžeme standardizovat indentation, delimiters, jak vypisovat key-value pairs, atd. Můžeme pak mít flagy pro změnu outputu, např. renderovat jako "pretty table" a nebo renderovat jako CSV pro processing v jiném commandu. Ale hlavně to bude pak konzistentní. Vytvořil jsem na to epic v maintenance https://keboola.atlassian.net/browse/KAC-268 (nevěděl jsem, kam jinam zařadit). Je to tak OK?

2022-10-10 11:46 UTC, JakubMatejka commented
Ano, souhlasím, koncepčně to řešme později. Ale říkám že než to tak uděláme, tak aspoň trochu zpřehledněme ten output. Nebo to je problém?

2022-10-10 11:53 UTC, JakubMatejka commented
Vždycky mě můžete overridenout, blokovat to zbytečně nechci. Jen nejsem úplně fanda konceptu "rychle mergovat, fixovat později", to pak nemusím dělat review. 🙂

2022-10-10 11:54 UTC, jprochazk commented
Je to problém, protože by bylo potřeba se shodnout na tom, co je "přehlednější", což je subjektivní věc. Budeme se točit pořád dokola a nebude to produktivní. Ta implementace je ale hotová, output minimálně obsahuuje všechny důležité informace a hlavně tohle blokuje další věci (což je moje chyba, měl jsem ty "unrelated" změny házet do jiných PR).

2022-10-10 11:59 UTC, JakubMatejka commented
Ve chvílích kdy je to subjektivní dávám přednost konzistenci a názoru vývojáře který za tím kódem stojí nejdýl, tak ať to rozhodne Michal. 😄

2022-10-10 12:21 UTC, jprochazk commented
> Tak co třeba dát první název jak píše Michal a ostatní parametry trochu upozadit, třeba oddělit závorkama

Stačí to tak?

2022-10-10 12:34 UTC, michaljurecko commented
Mne staci, ze bude ten `name` prvy :wink:

2022-10-10 12:36 UTC, JakubMatejka commented
Jo jo, taky tak. 🙂 👍

2022-10-10 12:37 UTC, JakubMatejka approved these changes
lgtm

2022-10-10 12:39 UTC, merged